"""add_unique_constraint_name_start_year_to_groups

Revision ID: 0066c2f194e3
Revises: a9231fce026c
Create Date: 2025-11-23 19:27:04.504392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0066c2f194e3"
down_revision: Union[str, Sequence[str], None] = "a9231fce026c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_name_start_year", "groups", ["name", "start_year"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_name_start_year", "groups", type_="unique")
    # ### end Alembic commands ###
