"""add_updated_at_to_groups

Revision ID: 08bb890e4ff6
Revises: 457fda4e1836
Create Date: 2025-10-19 20:42:28.592190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08bb890e4ff6"
down_revision: Union[str, Sequence[str], None] = "457fda4e1836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("content_weights_content_type_key"), "content_weights", type_="unique"
    )
    op.drop_index(op.f("ix_content_weights_content_type"), table_name="content_weights")
    op.create_index(
        op.f("ix_content_weights_content_type"),
        "content_weights",
        ["content_type"],
        unique=True,
    )
    op.add_column("groups", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "updated_at")
    op.drop_index(op.f("ix_content_weights_content_type"), table_name="content_weights")
    op.create_index(
        op.f("ix_content_weights_content_type"),
        "content_weights",
        ["content_type"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("content_weights_content_type_key"),
        "content_weights",
        ["content_type"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
