"""add_timer_and_autosave_fields_to_test_attempts

Revision ID: 1c409b4aeb57
Revises: 4dbda14de50a
Create Date: 2025-11-11 00:30:28.136417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c409b4aeb57"
down_revision: Union[str, Sequence[str], None] = "4dbda14de50a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование индексов перед удалением
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    if inspector.has_table("question_bank_entries"):
        # Удаляем индексы только если таблица существует
        op.drop_index(
            op.f("ix_question_bank_entries_created_by"),
            table_name="question_bank_entries",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_question_bank_entries_section_id"),
            table_name="question_bank_entries",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_question_bank_entries_topic_id"),
            table_name="question_bank_entries",
            if_exists=True,
        )
        op.drop_table("question_bank_entries")
    else:
        print(
            "Таблица question_bank_entries уже удалена, пропускаем удаление индексов и таблицы"
        )
    op.add_column(
        "test_attempts", sa.Column("last_activity_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "test_attempts", sa.Column("expires_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "test_attempts", sa.Column("auto_extend_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "test_attempts", sa.Column("last_save_at", sa.DateTime(), nullable=True)
    )
    op.add_column("test_attempts", sa.Column("draft_answers", sa.JSON(), nullable=True))
    op.add_column(
        "test_attempts", sa.Column("cleanup_scheduled_at", sa.DateTime(), nullable=True)
    )
    op.drop_index(op.f("ix_test_questions_question_id"), table_name="test_questions")
    op.drop_index(op.f("ix_test_questions_test_id"), table_name="test_questions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_test_questions_test_id"), "test_questions", ["test_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_questions_question_id"),
        "test_questions",
        ["question_id"],
        unique=False,
    )
    op.drop_column("test_attempts", "cleanup_scheduled_at")
    op.drop_column("test_attempts", "draft_answers")
    op.drop_column("test_attempts", "last_save_at")
    op.drop_column("test_attempts", "auto_extend_count")
    op.drop_column("test_attempts", "expires_at")
    op.drop_column("test_attempts", "last_activity_at")
    op.create_table(
        "question_bank_entries",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("topic_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("section_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("question", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "question_type",
            postgresql.ENUM(
                "SINGLE_CHOICE", "MULTIPLE_CHOICE", "OPEN_TEXT", name="questiontype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "options",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "correct_answer",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("hint", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_final", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "tags",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("is_archived", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("question_bank_entries_created_by_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("question_bank_entries_section_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("question_bank_entries_topic_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("question_bank_entries_pkey")),
    )
    op.create_index(
        op.f("ix_question_bank_entries_topic_id"),
        "question_bank_entries",
        ["topic_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_entries_section_id"),
        "question_bank_entries",
        ["section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_bank_entries_created_by"),
        "question_bank_entries",
        ["created_by"],
        unique=False,
    )
    # ### end Alembic commands ###
