"""add_weight_to_subsections

Revision ID: 3a6fe9aeba5c
Revises: 0c8ee67e2491
Create Date: 2025-10-18 14:02:42.409573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a6fe9aeba5c"
down_revision: Union[str, Sequence[str], None] = "0c8ee67e2491"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем колонку как nullable
    op.add_column("subsections", sa.Column("weight", sa.Float(), nullable=True))

    # Заполняем существующие записи значениями по умолчанию
    op.execute("UPDATE subsections SET weight = 1.0 WHERE weight IS NULL")

    # Делаем колонку NOT NULL
    op.alter_column("subsections", "weight", nullable=False)
    op.alter_column(
        "tests",
        "is_final",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("topics", "creator_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(
        op.f("ix_topics_creator_id"), "topics", ["creator_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topics_creator_id"), table_name="topics")
    op.alter_column("topics", "creator_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "tests",
        "is_final",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_column("subsections", "weight")
    # ### end Alembic commands ###
