"""add_content_weights_table

Revision ID: 457fda4e1836
Revises: 3a6fe9aeba5c
Create Date: 2025-10-18 14:19:53.191132

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "457fda4e1836"
down_revision: Union[str, Sequence[str], None] = "3a6fe9aeba5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Убеждаемся, что enum `contenttype` существует (создаем, если отсутствует)
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_type WHERE typname = 'contenttype'
            ) THEN
                CREATE TYPE contenttype AS ENUM (
                    'SUBSECTION_TEXT',
                    'SUBSECTION_PDF',
                    'SUBSECTION_VIDEO',
                    'TEST_HINTED',
                    'TEST_SECTION_FINAL',
                    'TEST_GLOBAL_FINAL'
                );
            END IF;
        END
        $$;
    """
    )

    # Создаем таблицу content_weights через raw SQL
    op.execute(
        """
        CREATE TABLE content_weights (
            id SERIAL PRIMARY KEY,
            content_type contenttype NOT NULL UNIQUE,
            weight FLOAT NOT NULL,
            description VARCHAR,
            created_at TIMESTAMP,
            updated_at TIMESTAMP,
            is_active BOOLEAN
        )
    """
    )

    op.create_index(
        op.f("ix_content_weights_content_type"),
        "content_weights",
        ["content_type"],
        unique=False,
    )

    # Заполняем дефолтными значениями
    op.execute(
        """
        INSERT INTO content_weights (content_type, weight, description, is_active) VALUES
        ('SUBSECTION_TEXT', 1.0, 'Текстовый подраздел', true),
        ('SUBSECTION_PDF', 1.5, 'PDF документ', true),
        ('SUBSECTION_VIDEO', 2.0, 'Видео', true),
        ('TEST_HINTED', 2.0, 'Тест с подсказками', true),
        ('TEST_SECTION_FINAL', 3.0, 'Финальный тест раздела', true),
        ('TEST_GLOBAL_FINAL', 3.0, 'Глобальный финальный тест', true)
    """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_weights_content_type"), table_name="content_weights")
    op.drop_table("content_weights")
    op.execute("DROP TYPE IF EXISTS contenttype")
    # ### end Alembic commands ###
