"""migrate_to_question_bank: add topic_id, section_id, created_by to questions, remove test_id, add test_questions table, update test model, add FAILED and EXPIRED to TestAttemptStatus

Revision ID: 4dbda14de50a
Revises: 4e5b24aab463
Create Date: 2025-11-10 23:56:18.168131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dbda14de50a"
down_revision: Union[str, Sequence[str], None] = "6ad2874ac1d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Проверяем существование таблицы test_questions
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    if not inspector.has_table("test_questions"):
        op.create_table(
            "test_questions",
            sa.Column("test_id", sa.Integer(), nullable=False),
            sa.Column("question_id", sa.Integer(), nullable=False),
            sa.Column("added_by", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(
                ["added_by"],
                ["users.id"],
            ),
            sa.ForeignKeyConstraint(
                ["question_id"],
                ["questions.id"],
            ),
            sa.ForeignKeyConstraint(
                ["test_id"],
                ["tests.id"],
            ),
            sa.PrimaryKeyConstraint("test_id", "question_id"),
        )
        print("Таблица test_questions создана")
    else:
        print("Таблица test_questions уже существует, пропускаем создание")
    # Добавляем индексы для производительности (если отсутствуют)
    op.create_index(
        op.f("ix_test_questions_test_id"),
        "test_questions",
        ["test_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_test_questions_question_id"),
        "test_questions",
        ["question_id"],
        unique=False,
        if_not_exists=True,
    )
    op.add_column("questions", sa.Column("topic_id", sa.Integer(), nullable=True))
    op.add_column("questions", sa.Column("section_id", sa.Integer(), nullable=True))
    op.add_column("questions", sa.Column("created_by", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_questions_test_id"), table_name="questions")
    op.create_index(
        op.f("ix_questions_created_by"), "questions", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_questions_section_id"), "questions", ["section_id"], unique=False
    )
    op.create_index(
        op.f("ix_questions_topic_id"), "questions", ["topic_id"], unique=False
    )
    op.drop_constraint(op.f("questions_test_id_fkey"), "questions", type_="foreignkey")
    op.create_foreign_key(None, "questions", "topics", ["topic_id"], ["id"])
    op.create_foreign_key(None, "questions", "users", ["created_by"], ["id"])
    op.create_foreign_key(None, "questions", "sections", ["section_id"], ["id"])
    op.drop_column("questions", "test_id")
    op.drop_column("tests", "target_questions")
    op.drop_index(
        op.f("ix_topic_authors_topic_user_archived"), table_name="topic_authors"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_topic_authors_topic_user_archived"),
        "topic_authors",
        ["topic_id", "user_id", "is_archived"],
        unique=False,
    )
    op.add_column(
        "tests",
        sa.Column("target_questions", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("test_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        op.f("questions_test_id_fkey"), "questions", "tests", ["test_id"], ["id"]
    )
    op.drop_index(op.f("ix_questions_topic_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_section_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_created_by"), table_name="questions")
    op.create_index(
        op.f("ix_questions_test_id"), "questions", ["test_id"], unique=False
    )
    op.drop_column("questions", "created_by")
    op.drop_column("questions", "section_id")
    op.drop_column("questions", "topic_id")
    op.drop_index(op.f("ix_test_questions_question_id"), table_name="test_questions")
    op.drop_index(op.f("ix_test_questions_test_id"), table_name="test_questions")
    op.drop_table("test_questions")
    # ### end Alembic commands ###
