"""Initial migration

Revision ID: 696706b223c4
Revises:
Create Date: 2025-09-09 19:05:00.197413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "696706b223c4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("end_year", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=False)
    op.create_index(
        op.f("ix_groups_start_year"), "groups", ["start_year"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "role", sa.Enum("ADMIN", "TEACHER", "STUDENT", name="role"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "group_students",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="groupstudentstatus"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("left_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.create_table(
        "group_teachers",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sections_topic_id"), "sections", ["topic_id"], unique=False
    )
    op.create_table(
        "topic_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("STARTED", "IN_PROGRESS", "COMPLETED", name="progressstatus"),
            nullable=False,
        ),
        sa.Column("completion_percentage", sa.Float(), nullable=True),
        sa.Column("last_accessed", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topic_progress_topic_id"), "topic_progress", ["topic_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_progress_user_id"), "topic_progress", ["user_id"], unique=False
    )
    op.create_table(
        "section_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("STARTED", "IN_PROGRESS", "COMPLETED", name="progressstatus"),
            nullable=False,
        ),
        sa.Column("completion_percentage", sa.Float(), nullable=True),
        sa.Column("last_accessed", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_section_progress_section_id"),
        "section_progress",
        ["section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_section_progress_user_id"),
        "section_progress",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "subsections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("TEXT", "VIDEO", "PDF", name="subsectiontype"),
            nullable=False,
        ),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subsections_section_id"), "subsections", ["section_id"], unique=False
    )
    op.create_table(
        "tests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("HINTED", "SECTION_FINAL", "GLOBAL_FINAL", name="testtype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("completion_percentage", sa.Float(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tests_section_id"), "tests", ["section_id"], unique=False)
    op.create_index(op.f("ix_tests_topic_id"), "tests", ["topic_id"], unique=False)
    op.create_index(op.f("ix_tests_type"), "tests", ["type"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "SINGLE_CHOICE", "MULTIPLE_CHOICE", "OPEN_TEXT", name="questiontype"
            ),
            nullable=False,
        ),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("correct_answer", sa.JSON(), nullable=True),
        sa.Column("hint", sa.String(), nullable=True),
        sa.Column("is_final", sa.Boolean(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("correct_answer_index", sa.Integer(), nullable=True),
        sa.Column("correct_answer_indices", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_test_id"), "questions", ["test_id"], unique=False
    )
    op.create_table(
        "subsection_progress",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subsection_id", sa.Integer(), nullable=False),
        sa.Column("is_viewed", sa.Boolean(), nullable=True),
        sa.Column("viewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["subsection_id"],
            ["subsections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subsection_progress_subsection_id"),
        "subsection_progress",
        ["subsection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subsection_progress_user_id"),
        "subsection_progress",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "test_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("time_spent", sa.Integer(), nullable=True),
        sa.Column("answers", sa.JSON(), nullable=True),
        sa.Column("randomized_config", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("STARTED", "IN_PROGRESS", "COMPLETED", name="testattemptstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["tests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_attempts_test_id"), "test_attempts", ["test_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_attempts_user_id"), "test_attempts", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_attempts_user_id"), table_name="test_attempts")
    op.drop_index(op.f("ix_test_attempts_test_id"), table_name="test_attempts")
    op.drop_table("test_attempts")
    op.drop_index(
        op.f("ix_subsection_progress_user_id"), table_name="subsection_progress"
    )
    op.drop_index(
        op.f("ix_subsection_progress_subsection_id"), table_name="subsection_progress"
    )
    op.drop_table("subsection_progress")
    op.drop_index(op.f("ix_questions_test_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_tests_type"), table_name="tests")
    op.drop_index(op.f("ix_tests_topic_id"), table_name="tests")
    op.drop_index(op.f("ix_tests_section_id"), table_name="tests")
    op.drop_table("tests")
    op.drop_index(op.f("ix_subsections_section_id"), table_name="subsections")
    op.drop_table("subsections")
    op.drop_index(op.f("ix_section_progress_user_id"), table_name="section_progress")
    op.drop_index(op.f("ix_section_progress_section_id"), table_name="section_progress")
    op.drop_table("section_progress")
    op.drop_index(op.f("ix_topic_progress_user_id"), table_name="topic_progress")
    op.drop_index(op.f("ix_topic_progress_topic_id"), table_name="topic_progress")
    op.drop_table("topic_progress")
    op.drop_index(op.f("ix_sections_topic_id"), table_name="sections")
    op.drop_table("sections")
    op.drop_table("topics")
    op.drop_table("group_teachers")
    op.drop_table("group_students")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_groups_start_year"), table_name="groups")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
