"""Add cascade delete for progress relationships

Revision ID: 90e9d75ab287
Revises: 5dd32b448c13
Create Date: 2025-11-04 21:03:28.757554

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "90e9d75ab287"
down_revision: Union[str, Sequence[str], None] = "5dd32b448c13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем CASCADE для topic_progress
    op.drop_constraint(
        "topic_progress_topic_id_fkey", "topic_progress", type_="foreignkey"
    )
    op.create_foreign_key(
        "topic_progress_topic_id_fkey",
        "topic_progress",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Добавляем CASCADE для section_progress
    op.drop_constraint(
        "section_progress_section_id_fkey", "section_progress", type_="foreignkey"
    )
    op.create_foreign_key(
        "section_progress_section_id_fkey",
        "section_progress",
        "sections",
        ["section_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Добавляем CASCADE для subsection_progress
    op.drop_constraint(
        "subsection_progress_subsection_id_fkey",
        "subsection_progress",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "subsection_progress_subsection_id_fkey",
        "subsection_progress",
        "subsections",
        ["subsection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Убираем CASCADE для subsection_progress
    op.drop_constraint(
        "subsection_progress_subsection_id_fkey",
        "subsection_progress",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "subsection_progress_subsection_id_fkey",
        "subsection_progress",
        "subsections",
        ["subsection_id"],
        ["id"],
    )

    # Убираем CASCADE для section_progress
    op.drop_constraint(
        "section_progress_section_id_fkey", "section_progress", type_="foreignkey"
    )
    op.create_foreign_key(
        "section_progress_section_id_fkey",
        "section_progress",
        "sections",
        ["section_id"],
        ["id"],
    )

    # Убираем CASCADE для topic_progress
    op.drop_constraint(
        "topic_progress_topic_id_fkey", "topic_progress", type_="foreignkey"
    )
    op.create_foreign_key(
        "topic_progress_topic_id_fkey", "topic_progress", "topics", ["topic_id"], ["id"]
    )
    # ### end Alembic commands ###
