"""restore_target_questions_to_tests

Revision ID: 991867b2bb61
Revises: e9d56fbd24db
Create Date: 2025-11-11 10:20:40.862761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "991867b2bb61"
down_revision: Union[str, Sequence[str], None] = "e9d56fbd24db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("target_questions", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tests", "target_questions")
    # ### end Alembic commands ###
