"""add_subsection_tracking_fields

Revision ID: 9eceec2d410e
Revises: ef2a58daa005
Create Date: 2025-11-04 19:59:32.213210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9eceec2d410e"
down_revision: Union[str, Sequence[str], None] = "ef2a58daa005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые поля в subsection_progress
    op.add_column(
        "subsection_progress",
        sa.Column("time_spent_seconds", sa.Integer(), nullable=True),
    )
    op.add_column(
        "subsection_progress",
        sa.Column("last_activity_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "subsection_progress",
        sa.Column("session_start_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "subsection_progress", sa.Column("is_completed", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "subsection_progress",
        sa.Column("completion_percentage", sa.Float(), nullable=True),
    )
    op.add_column(
        "subsection_progress", sa.Column("activity_sessions", sa.JSON(), nullable=True)
    )

    # Устанавливаем значения по умолчанию для существующих записей
    op.execute(
        "UPDATE subsection_progress SET time_spent_seconds = 0 WHERE time_spent_seconds IS NULL"
    )
    op.execute(
        "UPDATE subsection_progress SET is_completed = false WHERE is_completed IS NULL"
    )
    op.execute(
        "UPDATE subsection_progress SET completion_percentage = 0.0 WHERE completion_percentage IS NULL"
    )

    # Для просмотренных подразделов устанавливаем is_completed = true и completion_percentage = 100
    op.execute(
        """
        UPDATE subsection_progress 
        SET is_completed = true, completion_percentage = 100.0 
        WHERE is_viewed = true AND is_completed = false
    """
    )

    # Добавляем новые поля в subsections
    op.add_column(
        "subsections", sa.Column("required_time_minutes", sa.Integer(), nullable=True)
    )
    op.add_column(
        "subsections", sa.Column("min_time_seconds", sa.Integer(), nullable=True)
    )

    # Устанавливаем значение по умолчанию для min_time_seconds
    op.execute(
        "UPDATE subsections SET min_time_seconds = 30 WHERE min_time_seconds IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subsections", "min_time_seconds")
    op.drop_column("subsections", "required_time_minutes")
    op.drop_column("subsection_progress", "activity_sessions")
    op.drop_column("subsection_progress", "completion_percentage")
    op.drop_column("subsection_progress", "is_completed")
    op.drop_column("subsection_progress", "session_start_at")
    op.drop_column("subsection_progress", "last_activity_at")
    op.drop_column("subsection_progress", "time_spent_seconds")
    # ### end Alembic commands ###
