"""make_section_id_required_for_questions

Revision ID: a9231fce026c
Revises: 991867b2bb61
Create Date: 2025-11-21 11:41:29.322310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9231fce026c"
down_revision: Union[str, Sequence[str], None] = "991867b2bb61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questions", "section_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "questions", "section_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
