"""Add group_topics table for topic-group assignments

Revision ID: add_group_topics_table
Revises: add_is_final_to_tests
Create Date: 2025-09-20 14:10:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add_group_topics_table"
down_revision: Union[str, Sequence[str], None] = "add_is_final_to_tests"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add group_topics table for topic-group assignments."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_topics",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "topic_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove group_topics table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_topics")
    # ### end Alembic commands ###
