"""Add is_final column to tests table

Revision ID: add_is_final_to_tests
Revises: 696706b223c4
Create Date: 2025-09-20 14:05:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add_is_final_to_tests"
down_revision: Union[str, Sequence[str], None] = "696706b223c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add is_final column to tests table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tests",
        sa.Column("is_final", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove is_final column from tests table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tests", "is_final")
    # ### end Alembic commands ###
