"""add_slides_field_to_subsections

Revision ID: e283aa54cab0
Revises: 6993b9f2fa91
Create Date: 2025-11-04 22:27:57.386029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e283aa54cab0"
down_revision: Union[str, Sequence[str], None] = "6993b9f2fa91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("section_progress_section_id_fkey"), "section_progress", type_="foreignkey"
    )
    op.create_foreign_key(None, "section_progress", "sections", ["section_id"], ["id"])
    op.drop_constraint(
        op.f("subsection_progress_subsection_id_fkey"),
        "subsection_progress",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "subsection_progress", "subsections", ["subsection_id"], ["id"]
    )
    op.add_column("subsections", sa.Column("slides", sa.JSON(), nullable=True))
    op.drop_constraint(
        op.f("topic_progress_topic_id_fkey"), "topic_progress", type_="foreignkey"
    )
    op.create_foreign_key(None, "topic_progress", "topics", ["topic_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "topic_progress", type_="foreignkey")
    op.create_foreign_key(
        op.f("topic_progress_topic_id_fkey"),
        "topic_progress",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("subsections", "slides")
    op.drop_constraint(None, "subsection_progress", type_="foreignkey")
    op.create_foreign_key(
        op.f("subsection_progress_subsection_id_fkey"),
        "subsection_progress",
        "subsections",
        ["subsection_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "section_progress", type_="foreignkey")
    op.create_foreign_key(
        op.f("section_progress_section_id_fkey"),
        "section_progress",
        "sections",
        ["section_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
