"""create_topic_authors_table

Revision ID: ebc44ab8c0f7
Revises: 1c409b4aeb57
Create Date: 2025-11-11 09:43:03.146690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebc44ab8c0f7"
down_revision: Union[str, Sequence[str], None] = "e283aa54cab0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Проверяем, существует ли таблица topic_authors
    connection = op.get_bind()
    inspector = sa.inspect(connection)

    if not inspector.has_table("topic_authors"):
        # Создаем таблицу только если она не существует
        op.create_table(
            "topic_authors",
            sa.Column("topic_id", sa.Integer(), nullable=False, index=True),
            sa.Column("user_id", sa.Integer(), nullable=False, index=True),
            sa.Column("added_by", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=True),
            sa.Column("is_archived", sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(
                ["added_by"],
                ["users.id"],
            ),
            sa.ForeignKeyConstraint(
                ["topic_id"],
                ["topics.id"],
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("topic_id", "user_id"),
        )
        op.create_index(
            op.f("ix_topic_authors_topic_id"),
            "topic_authors",
            ["topic_id"],
            unique=False,
            if_not_exists=True,
        )
        op.create_index(
            op.f("ix_topic_authors_user_id"),
            "topic_authors",
            ["user_id"],
            unique=False,
            if_not_exists=True,
        )
        print("Таблица topic_authors создана")
    else:
        print("Таблица topic_authors уже существует, пропускаем создание")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topic_authors_user_id"), table_name="topic_authors")
    op.drop_index(op.f("ix_topic_authors_topic_id"), table_name="topic_authors")
    op.drop_table("topic_authors")
    # ### end Alembic commands ###
