"""add_assigned_at_to_group_teachers

Revision ID: ef2a58daa005
Revises: fc1209f9acbc
Create Date: 2025-10-19 20:49:37.793410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef2a58daa005"
down_revision: Union[str, Sequence[str], None] = "fc1209f9acbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_teachers", sa.Column("assigned_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group_teachers", "assigned_at")
    # ### end Alembic commands ###
