"""add_creator_id_to_groups

Revision ID: fc1209f9acbc
Revises: 08bb890e4ff6
Create Date: 2025-10-19 20:46:52.459780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc1209f9acbc"
down_revision: Union[str, Sequence[str], None] = "08bb890e4ff6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("creator_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_groups_creator_id"), "groups", ["creator_id"], unique=False
    )
    op.create_foreign_key(None, "groups", "users", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.drop_index(op.f("ix_groups_creator_id"), table_name="groups")
    op.drop_column("groups", "creator_id")
    # ### end Alembic commands ###
